
Jupyter server is running on: cs230.hpc.nyu.edu
Job starts at: Tue Nov 29 15:01:04 EST 2022

Step 1 :

If you are working in NYU campus, please open an iTerm window, run command

ssh -L 37725:localhost:37725 yk2516@greene.hpc.nyu.edu

If you are working off campus, you should already have ssh tunneling setup through HPC bastion host, 
that you can directly login to greene with command

ssh yk2516@greene

Please open an iTerm window, run command

ssh -L 37725:localhost:37725 yk2516@greene

Step 2:

Keep the iTerm windows in the previouse step open. Now open browser, find the line with

The Jupyter Notebook is running at: cs230.hpc.nyu.edu

the URL is something: http://localhost:37725/?token=XXXXXXXX (see your token below)

you should be able to connect to jupyter notebook running remotly on greene compute node with above url

[I 15:01:09.799 NotebookApp] Writing notebook server cookie secret to /home/yk2516/.local/share/jupyter/runtime/notebook_cookie_secret
[I 15:01:10.188 NotebookApp] Serving notebooks from local directory: /scratch/yk2516/currency-change-point-detection
[I 15:01:10.188 NotebookApp] Jupyter Notebook 6.1.5 is running at:
[I 15:01:10.188 NotebookApp] http://localhost:37725/?token=95c6a6f908cc2c3a3bf6061a798d58515f322c6832a1e81b
[I 15:01:10.188 NotebookApp]  or http://127.0.0.1:37725/?token=95c6a6f908cc2c3a3bf6061a798d58515f322c6832a1e81b
[I 15:01:10.188 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:01:10.192 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/yk2516/.local/share/jupyter/runtime/nbserver-2550230-open.html
    Or copy and paste one of these URLs:
        http://localhost:37725/?token=95c6a6f908cc2c3a3bf6061a798d58515f322c6832a1e81b
     or http://127.0.0.1:37725/?token=95c6a6f908cc2c3a3bf6061a798d58515f322c6832a1e81b
[I 15:03:29.774 NotebookApp] 302 GET /?token=95c6a6f908cc2c3a3bf6061a798d58515f322c6832a1e81b (127.0.0.1) 0.44ms
[I 15:03:46.166 NotebookApp] New terminal with automatic name: 1
[I 15:57:24.668 NotebookApp] EOF on FD 17; stopping reading
[I 15:57:24.769 NotebookApp] Terminal 1 closed
[I 16:01:14.806 NotebookApp] New terminal with automatic name: 1
[I 16:07:24.581 NotebookApp] EOF on FD 17; stopping reading
[I 16:07:24.682 NotebookApp] Terminal 1 closed
[I 16:08:41.118 NotebookApp] New terminal with automatic name: 1
[I 16:14:33.888 NotebookApp] EOF on FD 11; stopping reading
[I 16:14:33.989 NotebookApp] Terminal 1 closed
[I 16:14:40.261 NotebookApp] Creating new notebook in 
[I 16:14:40.307 NotebookApp] Writing notebook-signing key to /home/yk2516/.local/share/jupyter/notebook_secret
[E 16:14:41.653 NotebookApp] Uncaught exception POST /api/sessions (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:37725', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/sessions/handlers.py", line 69, in post
        model = yield maybe_future(
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 100, in start_kernel_for_session
        kernel_id = yield maybe_future(
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py", line 176, in start_kernel
        kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 185, in start_kernel
        km.start_kernel(**kwargs)
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/manager.py", line 309, in start_kernel
        kernel_cmd, kw = self.pre_start_kernel(**kw)
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/manager.py", line 256, in pre_start_kernel
        self.write_connection_file()
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/connect.py", line 468, in write_connection_file
        self.connection_file, cfg = write_connection_file(self.connection_file,
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/connect.py", line 138, in write_connection_file
        with secure_write(fname) as f:
      File "/ext3/miniconda3/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_core/paths.py", line 463, in secure_write
        with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/yk2516/.local/share/jupyter/runtime/kernel-88f095c2-b410-4709-8587-226d0a172101.json'
[W 16:14:41.659 NotebookApp] Unhandled error
[E 16:14:41.660 NotebookApp] {
      "Host": "localhost:37725",
      "Connection": "keep-alive",
      "Content-Length": "91",
      "Sec-Ch-Ua": "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|da5925cb|7f199d0e88a9a98f03edc8703779de4c|1669752209",
      "Sec-Ch-Ua-Platform": "\"macOS\"",
      "Origin": "http://localhost:37725",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:37725/notebooks/Untitled.ipynb?kernel_name=python3",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh-TW;q=0.7,zh;q=0.6",
      "Cookie": "username-localhost-37725=\"2|1:0|10:1669752209|24:username-localhost-37725|44:YWQ4YTg0NzE2Y2E2NGY5YWI1ZTQ3MjRiOWQzNTBmMjE=|204da894919b0a1a89bd8c3d2f260481312b3c84454143f276bf1d598aa9fc0f\"; _xsrf=2|da5925cb|7f199d0e88a9a98f03edc8703779de4c|1669752209"
    }
[E 16:14:41.660 NotebookApp] 500 POST /api/sessions (127.0.0.1) 98.21ms referer=http://localhost:37725/notebooks/Untitled.ipynb?kernel_name=python3
[I 16:14:50.940 NotebookApp] Saving file at /Untitled.ipynb
[E 16:14:51.257 NotebookApp] Uncaught exception POST /api/sessions (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:37725', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/sessions/handlers.py", line 69, in post
        model = yield maybe_future(
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 100, in start_kernel_for_session
        kernel_id = yield maybe_future(
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py", line 176, in start_kernel
        kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 185, in start_kernel
        km.start_kernel(**kwargs)
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/manager.py", line 309, in start_kernel
        kernel_cmd, kw = self.pre_start_kernel(**kw)
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/manager.py", line 256, in pre_start_kernel
        self.write_connection_file()
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/connect.py", line 468, in write_connection_file
        self.connection_file, cfg = write_connection_file(self.connection_file,
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/connect.py", line 138, in write_connection_file
        with secure_write(fname) as f:
      File "/ext3/miniconda3/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_core/paths.py", line 463, in secure_write
        with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/yk2516/.local/share/jupyter/runtime/kernel-46e49fcc-372c-48a5-8b36-5e9b18718608.json'
[W 16:14:51.258 NotebookApp] Unhandled error
[E 16:14:51.258 NotebookApp] {
      "Host": "localhost:37725",
      "Connection": "keep-alive",
      "Content-Length": "91",
      "Sec-Ch-Ua": "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|da5925cb|7f199d0e88a9a98f03edc8703779de4c|1669752209",
      "Sec-Ch-Ua-Platform": "\"macOS\"",
      "Origin": "http://localhost:37725",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:37725/notebooks/Untitled.ipynb?kernel_name=python3",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh-TW;q=0.7,zh;q=0.6",
      "Cookie": "username-localhost-37725=\"2|1:0|10:1669752209|24:username-localhost-37725|44:YWQ4YTg0NzE2Y2E2NGY5YWI1ZTQ3MjRiOWQzNTBmMjE=|204da894919b0a1a89bd8c3d2f260481312b3c84454143f276bf1d598aa9fc0f\"; _xsrf=2|da5925cb|7f199d0e88a9a98f03edc8703779de4c|1669752209"
    }
[E 16:14:51.258 NotebookApp] 500 POST /api/sessions (127.0.0.1) 3.60ms referer=http://localhost:37725/notebooks/Untitled.ipynb?kernel_name=python3
[W 16:14:59.173 NotebookApp] delete /Untitled.ipynb
[W 16:14:59.174 NotebookApp] Skipping trash for /scratch/yk2516/currency-change-point-detection/Untitled.ipynb, on different device to home directory
[I 16:15:02.092 NotebookApp] Creating new notebook in 
[E 16:15:02.702 NotebookApp] Uncaught exception POST /api/sessions (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:37725', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/sessions/handlers.py", line 69, in post
        model = yield maybe_future(
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 100, in start_kernel_for_session
        kernel_id = yield maybe_future(
      File "/ext3/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/ext3/miniconda3/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py", line 176, in start_kernel
        kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 185, in start_kernel
        km.start_kernel(**kwargs)
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/manager.py", line 309, in start_kernel
        kernel_cmd, kw = self.pre_start_kernel(**kw)
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/manager.py", line 256, in pre_start_kernel
        self.write_connection_file()
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/connect.py", line 468, in write_connection_file
        self.connection_file, cfg = write_connection_file(self.connection_file,
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_client/connect.py", line 138, in write_connection_file
        with secure_write(fname) as f:
      File "/ext3/miniconda3/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/ext3/miniconda3/lib/python3.8/site-packages/jupyter_core/paths.py", line 463, in secure_write
        with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/yk2516/.local/share/jupyter/runtime/kernel-c0ddee01-d40b-486f-932d-35afcd070acc.json'
[W 16:15:02.703 NotebookApp] Unhandled error
[E 16:15:02.703 NotebookApp] {
      "Host": "localhost:37725",
      "Connection": "keep-alive",
      "Content-Length": "91",
      "Sec-Ch-Ua": "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|da5925cb|7f199d0e88a9a98f03edc8703779de4c|1669752209",
      "Sec-Ch-Ua-Platform": "\"macOS\"",
      "Origin": "http://localhost:37725",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:37725/notebooks/Untitled.ipynb?kernel_name=python3",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8,zh-TW;q=0.7,zh;q=0.6",
      "Cookie": "username-localhost-37725=\"2|1:0|10:1669752209|24:username-localhost-37725|44:YWQ4YTg0NzE2Y2E2NGY5YWI1ZTQ3MjRiOWQzNTBmMjE=|204da894919b0a1a89bd8c3d2f260481312b3c84454143f276bf1d598aa9fc0f\"; _xsrf=2|da5925cb|7f199d0e88a9a98f03edc8703779de4c|1669752209"
    }
[E 16:15:02.703 NotebookApp] 500 POST /api/sessions (127.0.0.1) 2.43ms referer=http://localhost:37725/notebooks/Untitled.ipynb?kernel_name=python3
[W 16:15:06.860 NotebookApp] delete /Untitled.ipynb
[W 16:15:06.860 NotebookApp] Skipping trash for /scratch/yk2516/currency-change-point-detection/Untitled.ipynb, on different device to home directory
[I 16:15:08.968 NotebookApp] New terminal with automatic name: 1
[I 16:16:58.705 NotebookApp] EOF on FD 21; stopping reading
[I 16:16:58.805 NotebookApp] Terminal 1 closed
[I 16:17:04.536 NotebookApp] New terminal with automatic name: 1
[I 16:18:12.679 NotebookApp] EOF on FD 20; stopping reading
[I 16:18:12.779 NotebookApp] Terminal 1 closed
slurmstepd: error: *** JOB 27481763 ON cs230 CANCELLED AT 2022-11-29T16:20:05 ***
